version: "3.7"
services:
    mosquitto:
        build: ./mosquitto
        image: mqtt-auth:mosquitto
        container_name: auth_mosquitto
        restart: always
        depends_on:
            - node-auth
        volumes:
            - ./mosquitto/conf:/etc/mosquitto
        ports:
            - 1883:1883
            - 8883:8883
    db:
        image: postgres:11-alpine
        container_name: auth_db
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - "/home/dave/Documents/Programming/MQTT-auth-server/db:/var/lib/postgresql/data"
    adminer:
        image: adminer:latest
        container_name: auth_adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db
    node-auth:
        build: ./node-auth
        image: mqtt-auth:node-auth
        container_name: auth_node-auth
        restart: always
        depends_on:
            - db
            - redis
        volumes:
            - ./node-auth/src:/usr/src/mqtt-auth/src
    node-sync:
        build: ./node-sync
        image: mqtt-auth:node-sync
        container_name: auth_node-sync
        restart: always
        depends_on:
            - redis
        volumes:
            - ./node-sync/src:/usr/src/mqtt-auth/src
    redis:
        image: redis:alpine
        container_name: auth_redis
        restart: always
